#ifndef CONFIG_H
#define CONFIG_H

#define TITLE "walker"
#define DEFAULT_WINDOW_WIDTH 1000
#define DEFAULT_WINDOW_HEIGHT 1000

#define NEAR_PLANE 0.01f
#define FAR_PLANE 6.0f

#define SSAO_KERNEL_SIZE 12
#define SSAO_NOISE_DIM 4
#define SSAO_RADIUS 0.3f
#define SSAO_BLUR_SCALE 4
#define SSAO_POWER 2.0f

#define GRAIN_INTESITY 0.25f
#define GRAIN_SIGNAL_TO_NOISE 4.0f
#define GRAIN_VARIANCE 0.15f
#define GRAIN_NOISE_SHIFT 0.0f

#endif