#ifndef VK_FUNCTIONS_H
#define VK_FUNCTIONS_H

#include <vulkan/vulkan.h>

#ifdef VK_NO_PROTOTYPES
// vulkan loader functions
extern PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr;
extern PFN_vkCreateInstance vkCreateInstance;

// vulkan instance functions
extern PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr;
extern PFN_vkGetPhysicalDeviceFormatProperties vkGetPhysicalDeviceFormatProperties;
extern PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties;
extern PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties;
extern PFN_vkCreateDevice vkCreateDevice;
extern PFN_vkGetPhysicalDeviceSurfaceSupportKHR vkGetPhysicalDeviceSurfaceSupportKHR;
extern PFN_vkGetPhysicalDeviceSurfacePresentModesKHR vkGetPhysicalDeviceSurfacePresentModesKHR;
extern PFN_vkGetPhysicalDeviceSurfaceFormatsKHR vkGetPhysicalDeviceSurfaceFormatsKHR;
extern PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
extern PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties;
extern PFN_vkEnumerateDeviceExtensionProperties vkEnumerateDeviceExtensionProperties;
extern PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices;
extern PFN_vkDestroyInstance vkDestroyInstance;

// vulkan device functions
extern PFN_vkCmdEndRenderingKHR vkCmdEndRenderingKHR;
extern PFN_vkCmdBeginRenderingKHR vkCmdBeginRenderingKHR;
extern PFN_vkCmdDrawIndexed vkCmdDrawIndexed;
extern PFN_vkCmdBindIndexBuffer vkCmdBindIndexBuffer;
extern PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers;
extern PFN_vkCmdCopyBuffer vkCmdCopyBuffer;
extern PFN_vkDestroySampler vkDestroySampler;
extern PFN_vkCreateSampler vkCreateSampler;
extern PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage;
extern PFN_vkInvalidateMappedMemoryRanges vkInvalidateMappedMemoryRanges;
extern PFN_vkFlushMappedMemoryRanges vkFlushMappedMemoryRanges;
extern PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements;
extern PFN_vkBindImageMemory vkBindImageMemory;
extern PFN_vkDestroyImage vkDestroyImage;
extern PFN_vkCreateImage vkCreateImage;
extern PFN_vkCmdPushConstants vkCmdPushConstants;
extern PFN_vkCmdPipelineBarrier vkCmdPipelineBarrier;
extern PFN_vkCmdDispatch vkCmdDispatch;
extern PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets;
extern PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets;
extern PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets;
extern PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout;
extern PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout;
extern PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool;
extern PFN_vkCreateDescriptorPool vkCreateDescriptorPool;
extern PFN_vkUnmapMemory vkUnmapMemory;
extern PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements;
extern PFN_vkBindBufferMemory vkBindBufferMemory;
extern PFN_vkMapMemory vkMapMemory;
extern PFN_vkFreeMemory vkFreeMemory;
extern PFN_vkAllocateMemory vkAllocateMemory;
extern PFN_vkDestroyBuffer vkDestroyBuffer;
extern PFN_vkCreateBuffer vkCreateBuffer;
extern PFN_vkDeviceWaitIdle vkDeviceWaitIdle;
extern PFN_vkEndCommandBuffer vkEndCommandBuffer;
extern PFN_vkBeginCommandBuffer vkBeginCommandBuffer;
extern PFN_vkCmdDraw vkCmdDraw;
extern PFN_vkCmdBindPipeline vkCmdBindPipeline;
extern PFN_vkAcquireNextImageKHR vkAcquireNextImageKHR;
extern PFN_vkResetFences vkResetFences;
extern PFN_vkWaitForFences vkWaitForFences;
extern PFN_vkQueuePresentKHR vkQueuePresentKHR;
extern PFN_vkQueueSubmit vkQueueSubmit;
extern PFN_vkDestroyFence vkDestroyFence;
extern PFN_vkCreateFence vkCreateFence;
extern PFN_vkDestroySemaphore vkDestroySemaphore;
extern PFN_vkCreateSemaphore vkCreateSemaphore;
extern PFN_vkFreeCommandBuffers vkFreeCommandBuffers;
extern PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers;
extern PFN_vkDestroyCommandPool vkDestroyCommandPool;
extern PFN_vkCreateCommandPool vkCreateCommandPool;
extern PFN_vkDestroyShaderModule vkDestroyShaderModule;
extern PFN_vkCreateShaderModule vkCreateShaderModule;
extern PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout;
extern PFN_vkCreatePipelineLayout vkCreatePipelineLayout;
extern PFN_vkDestroyPipeline vkDestroyPipeline;
extern PFN_vkCreateComputePipelines vkCreateComputePipelines;
extern PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines;
extern PFN_vkDestroyImageView vkDestroyImageView;
extern PFN_vkCreateImageView vkCreateImageView;
extern PFN_vkGetSwapchainImagesKHR vkGetSwapchainImagesKHR;
extern PFN_vkDestroySwapchainKHR vkDestroySwapchainKHR;
extern PFN_vkCreateSwapchainKHR vkCreateSwapchainKHR;
extern PFN_vkGetDeviceQueue vkGetDeviceQueue;
extern PFN_vkDestroyDevice vkDestroyDevice;
#endif

void loadVulkanLoaderFunctions();
void loadVulkanInstanceFunctions(VkInstance instance);
void loadVulkanDeviceFunctions(VkDevice device);

#endif
